version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      POSTGRES_USER: bookshopuser
      POSTGRES_PASSWORD: bookshoppassword
      POSTGRES_DB: bookshopdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  test_db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: bookshop_test
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d bookshop_test" ]
      interval: 3s
      retries: 5
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app/app
    environment:
      DATABASE_URL: postgresql+asyncpg://bookshopuser:bookshoppassword@db:5432/bookshopdb
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: