name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Start Docker Compose services
        run: docker-compose up -d test_db

      - name: Wait for test_db to be healthy
        run: |
          for i in {1..10}; do
            docker compose exec test_db pg_isready -U test -d bookshop_test && break
            sleep 3
          done

      - name: Run tests
        run: coverage run -m pytest

      - name: Check test coverage
        run: coverage report --fail-under=80

      - name: Build Docker image
        run: docker build -t bookshop:latest .
